### ISSUE TITLE
TypeError: fs.watch is not a function

### ISSUE THREAD

**Issue by siuying** [RangerMauve/dat-archive-web#11]
When I try to create a html based on example in README:

```html
<html>
    <head>
        <script src="//unpkg.com/dat-archive-web/bundle.js"></script>
    </head>
    <body>
        <script>
            // After including the bundle in a script tag, or requiring it
            const archive = new DatArchive('dat://87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336')

            // Subscribe to network events
            archive.addEventListener("download", ({bytes}) => console.log(`Downloaded ${bytes} bytes`))

            // Subscribe to file events
            const emitter = archive.watch("/path/to/watch")
            emitter.addEventListener("change", ({path}) => console.log(`file at path: ${path} changed!`))

            archive.readFile('/index.html')
            .then((html) => console.log(html))
        </script>
    </body>
</html>
```

The page throw error: `TypeError: fs.watch is not a function`. I've tried this on Firefox and Chrome, both return same error.

**Comment by RangerMauve** [comment]
Would you mind posting a stack trace? Ideally `fs` shouldn't be getting used at all. :P

**Comment by RangerMauve** [comment]
Oh dang. It looks to be a race condition since the archive isn't fully 'loaded' yet.

Try using this code for loading the archive for now

```js
const archive = await DatArchive.load('dat://whatever')
```

**Comment by RangerMauve** [comment]
Thank you for reporting this!

This should be fixed in Version 2.0.5 😁

**Comment by siuying** [comment]
Thanks a lot!

**Comment by siuying** [comment]
Now I get an error "Error: File not found" at `bundle.js:5305:5`

<img width="1364" alt="" src="https://user-images.githubusercontent.com/8608/62593339-e850d800-b908-11e9-9095-503d2372d252.png">

**Comment by RangerMauve** [comment]
Weird. You might want to add a short delay before trying to read anything from the archive so that the metadata can download.

**Comment by RangerMauve** [comment]
Else I'd check if the data _ever_ gets loaded and that the archive is pinned somewhere.

**Comment by siuying** [comment]
Thanks. I suspects the given example have no peers. I tried to shared something on Beaker but I still get same errors. Would you have any feeds that is working from your side?

**Comment by RangerMauve** [comment]
Yeah, sadly the browser version is still having trouble loading archives that are just in home networks, I find that opening an archive in https://gateway.mauve.moe/ can help and also pinning archives to hashbase or a dat-store instance on a server.
