### ISSUE TITLE
D-A-Web into Dat/SDK?

### ISSUE THREAD

**Issue by DougAnderson444** [RangerMauve/dat-archive-web#12]
I saw the integration of `DatArchive` for Beaker into the SDK 

Any plans to also put this `dat-archive-web` into the SDK?  I am thinking it may be useful for those who want to use the Beaker API, and WebDB API, in a regular browser.

Thoughts?

**Comment by RangerMauve** [comment]
Yeah, the promise API in the SDK is based on dat-archive-web.

So something like `const {DatArchive} = require('dat-sdk/auto')` should do the trick.
