### ISSUE TITLE
Use in VUE CLI app - TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by RobertoSnap** [RangerMauve/dat-archive-web#6]
# Goal
Setup node-dat-archive and use it from a browser with dat-archive-web

# Steps
1. node-dat-archive running locally.
2. Createn VUE application with 
   ```npm install -g @vue/cli```
   ```npm install --save dat-archive-web```
   ```vue create dat-test ```
3. Change ./src/views/home.vue
```javascript
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/components/HelloWorld.vue'
const DatArchive = require('dat-archive-web')

export default {
  name: 'home',
  components: {
    HelloWorld
  },
  async created () {
    console.log("Created ran")

    const archive = new DatArchive('dat://87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336')
    console.log(await archive.readdir('/'))
  }
}
</script>
```
3. Run it in development mode   ``` npm run serve```

## Error 
[https://i.imgur.com/D5VKM4M.png](https://i.imgur.com/D5VKM4M.png)
polyfills.js?a0a3:32 Uncaught TypeError: Cannot read property 'match' of undefined
    at patch (polyfills.js?a0a3:32)
    at patch (graceful-fs.js?0da7:58)
    at Object.eval (graceful-fs.js?0da7:27)
    at eval (graceful-fs.js:264)
    at Object../node_modules/graceful-fs/graceful-fs.js (app.js:3522)
    at __webpack_require__ (app.js:768)
    at fn (app.js:131)
    at eval (index.js?bf81:4)
    at Object../node_modules/pauls-dat-api/node_modules/fs-extra/lib/fs/index.js (app.js:5068)
    at __webpack_require__ (app.js:768)

## Fiddle

Tried recreating it in FiddleJs but did not manage

[Fiddle](https://jsfiddle.net/RAHP/50wL7mdz/762908/)

**Comment by RangerMauve** [comment]
I think the problem is that the polyfill is expecting the page to be loaded from a gateway, since you're probably loading off of localhost, it's throwing an error. Try specifying a `DEFAULT_DAT_GATEWAY` global variable pointing to the gateway you want to use. Mak sure it's defined before you load the polyfill.

**Comment by RobertoSnap** [comment]
> I think the problem is that the polyfill is expecting the page to be loaded from a gateway, since you're probably loading off of localhost, it's throwing an error. Try specifying a `DEFAULT_DAT_GATEWAY` global variable pointing to the gateway you want to use. Mak sure it's defined before you load the polyfill.

Tried this, but had no effect. You can close the issue, im will try it another time with something simple.

**Comment by RangerMauve** [comment]
Dang! Sorry to hear that it didn't work out. 🙁

**Comment by ge-wang63** [comment]
Is this problem solved？

**Comment by RangerMauve** [comment]
@FuPingstar I suggest checking out the [Dat SDK](https://github.com/datproject/sdk) instead. Specifically the latest version being worked on in [this branch](https://github.com/datproject/sdk/tree/dat2-take-two)
