### ISSUE TITLE
#createFileActivityStream #createNetworkActivityStream throw "fs.watch is not a function" error

### ISSUE THREAD

**Issue by saimonmoore** [RangerMauve/dat-archive-web#9]
When I attempt to listen for network or file events via:

`#createFileActivityStream` or  `#createNetworkActivityStream` I get the following error:

<img width="1680" alt="Screenshot 2019-06-29 at 22 36 14" src="https://user-images.githubusercontent.com/494/60389258-0aac3600-9abf-11e9-9367-6816e3963923.png">

from here:
<img width="1401" alt="Screenshot 2019-06-29 at 22 35 27" src="https://user-images.githubusercontent.com/494/60389262-1bf54280-9abf-11e9-95ab-6d757894d531.png">

From the code:

<img width="1449" alt="Screenshot 2019-06-29 at 22 34 39" src="https://user-images.githubusercontent.com/494/60389277-392a1100-9abf-11e9-887c-e43d155f23bc.png">

it looks like it decides wether to look up the the data from the disk, locally in the browser or remotely depending on wether the `key` is present in the archive but in this case it's not.

<img width="434" alt="Screenshot 2019-06-29 at 22 35 01" src="https://user-images.githubusercontent.com/494/60389287-5f4fb100-9abf-11e9-9fe1-8803982167e9.png">

The exception breaks the app but it appears the event listeners were added as I'm seeing some network events:

<img width="1680" alt="Screenshot 2019-06-29 at 22 36 14" src="https://user-images.githubusercontent.com/494/60389294-6a0a4600-9abf-11e9-8426-e72a41183366.png">
<img width="1668" alt="Screenshot 2019-06-30 at 10 13 43" src="https://user-images.githubusercontent.com/494/60394144-f9dfdc80-9b1f-11e9-8f41-76b8e91d1825.png">

But as you can see from this trace, the `key` attribute is returned by the `getInfo` function but it doesn't appear to be in the dat archive object (or it's somehow added later...):

<img width="1680" alt="Screenshot 2019-06-29 at 22 47 23" src="https://user-images.githubusercontent.com/494/60389358-41cf1700-9ac0-11e9-9a30-775ced487d0d.png">

You can reproduce this with this branch (see last commit):

https://gitlab.com/saimonmoore/dlynx/tree/createNetworkActivityStreamIssue

**Comment by saimonmoore** [comment]
cc @RangerMauve

**Comment by RangerMauve** [comment]
Looking into this today

**Comment by RangerMauve** [comment]
Try using `DatArchive.load()` or `DatArchive.create()` to initialize your archive instead.

**Comment by saimonmoore** [comment]
I’m currently using DatArchive.create if no dat exists locally and
otherwise I use the constructor. I believe I tried DatArchive.load but if I
recall it hadn’t been implemented maybe?

**Comment by RangerMauve** [comment]
Oh weird! `.load` should have been present. :P That's a pretty big bug. I'll quickly update that.

**Comment by saimonmoore** [comment]
The other thing I was wondering was why the api change wrt to beaker for
these 2 functions ?

At some point I’d like to be able to try and get this running on beaker as
well :)

But I got quite far already this weekend...really just need to setup a
friends system (I’ll need the events for this), add search and filtering
and then perhaps a proxy server from which I can proxy from mobile.

**Comment by saimonmoore** [comment]
Awesome :)

**Comment by RangerMauve** [comment]
`DatArchive.load` not being there was an oversight, but the other two are on purpose since they've been deprecated in Beaker.

You're expected to be using `archive.watch()` now, I think. https://beakerbrowser.com/docs/apis/dat#watch

ping @pfrazee

**Comment by saimonmoore** [comment]
Aah I’ll check for  #watch tonight

**Comment by saimonmoore** [comment]
Thanks a lot :)

**Comment by RangerMauve** [comment]
Just pushed out 2.0.2 which has `DatArchive.load()` :)

**Comment by saimonmoore** [comment]
Geez that was quick :) Thanks a lot

Will try later on tonight

**Comment by saimonmoore** [comment]
@RangerMauve `DatArchive.load` seemed to do the trick however I noticed that there isn't any `archive.watch` currently implemented.

**Comment by RangerMauve** [comment]
Shoot. I could have sworn I had done something already. 😅

I'm a little busy with the SDK at the moment, but it should be possible to port over [the work paul did here](https://github.com/beakerbrowser/dat-node/blob/master/lib/dat-archive.js#L203) into dat-archive-web if you're for taking a shot at it. 😁

**Comment by saimonmoore** [comment]
Yep. Will try. Thanks for the hint.

**Comment by saimonmoore** [comment]
I've got something together but not sure it's working as I see no events 😅 so digging into it...

**Comment by saimonmoore** [comment]
Here: https://github.com/RangerMauve/dat-archive-web/pull/10

**Comment by RangerMauve** [comment]
Awesome, thank you so much for the fix! :D
